### PR TITLE
Renamed: message to _validationMessage and locale to _locale

### PR DESCRIPTION
**Pull request by michaelw8**
Message and locale are very generic property names that very easily conflict with attributes/relations on models. Because this mixin is meant to be added to every model, I want to make the names private and more scoped.

This also fixes issue #65

### CODE REVIEW

**Comment by esbanarango** [comment]
@michaelw8 This change makes totally sense 👌. Could we check and update the tests 🙏?

**Comment by esbanarango** [comment]
Looks like we still have some failures. https://travis-ci.org/esbanarango/ember-model-validator/jobs/554414292

**Comment by Haz901** [comment]
I had a look at this as well, and the tests seem to be failing on the master branch with the same errors as on this PR. They only fail when using `ember try`, everything seems fine with a regular `ember test`.

**Comment by Haz901** [comment]
Disregard my last, everything seems fine now(?) I'm not sure if it was an error on my part or there was some glitch in the ecosystem

**Comment by michaelw8** [comment]
@esbanarango after rerunning Travis the tests turned green ;-) Thanks for approving these changes.

**Comment by michaelw8** [comment]
@esbanarango Do you mind to release a new version of the addon so I can use these changes in our application? Thank you in advance 😄

**Comment by esbanarango** [comment]
@michaelw8 Totally. Putting it now.

**Comment by esbanarango** [comment]
@michaelw8 Version [3.9.0](https://www.npmjs.com/package/ember-model-validator/v/3.9.0) has been released. Thank you very much for this PR.

**Pull request merged**
